  services:
    postgres:
      image: postgres:latest
      container_name: API-HOTEL
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: hotel_db
      ports:
        - "5434:5432"
      volumes:
        - postgres_data:/var/lib/postgresql
      restart: always

  volumes:
    postgres_data: