spring.application.name=API_HOTEL
server.port=8030

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Max size per individual file
spring.servlet.multipart.max-file-size=10MB

# Max total request size for multiple files
spring.servlet.multipart.max-request-size=50MB

# Custom directory path where uploaded files will be stored
file.upload-dir=uploads/rooms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true